// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pinterest.Models;

#nullable disable

namespace Pinterest.Migrations
{
    [DbContext(typeof(PinterestDbContext))]
    [Migration("20250728193707_InitialModel")]
    partial class InitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PastaPin", b =>
                {
                    b.Property<Guid>("PastasID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PinsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PastasID", "PinsID");

                    b.HasIndex("PinsID");

                    b.ToTable("PastaPin");
                });

            modelBuilder.Entity("Pinterest.Models.Pasta", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProfileID");

                    b.ToTable("Pastas");
                });

            modelBuilder.Entity("Pinterest.Models.Pin", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProfileID");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("Pinterest.Models.Profile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("PastaPin", b =>
                {
                    b.HasOne("Pinterest.Models.Pasta", null)
                        .WithMany()
                        .HasForeignKey("PastasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pinterest.Models.Pin", null)
                        .WithMany()
                        .HasForeignKey("PinsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pinterest.Models.Pasta", b =>
                {
                    b.HasOne("Pinterest.Models.Profile", "Author")
                        .WithMany("Pastas")
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Pinterest.Models.Pin", b =>
                {
                    b.HasOne("Pinterest.Models.Profile", "Author")
                        .WithMany("CreatedPins")
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Pinterest.Models.Profile", b =>
                {
                    b.Navigation("CreatedPins");

                    b.Navigation("Pastas");
                });
#pragma warning restore 612, 618
        }
    }
}
